trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  - group: Polaris

steps:
- script: |
    mvn --version
    java --version
  displayName: 'Version check'

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '23'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
  displayName: 'Install Java'

- task: BlackDuckSecurityScan@2
  inputs:
    scanType: 'polaris'
    polarisServerUrl: 'https://poc.polaris.blackduck.com'
    polarisAccessToken: '$(POLARIS_ACCESSTOKEN)'
    polarisAssessmentTypes: 'SAST,SCA'
    polarisTestScaType: 'SCA-Package,SCA-Signature'
    polarisApplicationName: 'Evan Onboarding'