trigger:

- none

pool:
  vmImage: ubuntu-latest

variables:
  - group: SCA

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '23'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
  displayName: 'Install Java'
- bash: |
    mvn spotless:apply
    mvn -N wrapper:wrapper
    chmod +x ./mvnw

- script: |
    java -version
  displayName: 'Print Java version'

- task: BlackDuckSecurityScan@2
  inputs:
    scanType: 'blackducksca'
    blackduckScaUrl: '$(SCA_URL)'
    blackduckScaToken: '$(SCA_ACCESS_TOKEN)'