# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  default

steps:
- script: |
    mvn --version
    java --version
  displayName: 'Version check'

- task: BlackDuckSecurityScan@2
  inputs:
    scanType: 'polaris'
    polarisServerUrl: 'https://poc.polaris.blackduck.com'
    polarisAccessToken: '$(POLARIS_ACCESSTOKEN)'
    polarisAssessmentTypes: 'SAST,SCA'
    polarisTestScaType: 'SCA-Package'
    polarisWaitForScan: false
    polarisApplicationName: 'Evan Onboarding'

- task: BlackDuckSecurityScan@2
  inputs:
    scanType: 'polaris'
    polarisServerUrl: 'https://poc.polaris.blackduck.com'
    polarisAccessToken: '$(POLARIS_ACCESSTOKEN)'
    polarisAssessmentTypes: 'SCA'
    polarisTestScaType: 'SCA-Signature'
    polarisWaitForScan: false
    polarisApplicationName: 'Evan Onboarding'