trigger:

- none

pool:
  vmImage: ubuntu-latest

variables:
  - group: SCA

steps:
#- task: JavaToolInstaller@0
#  inputs:
#    versionSpec: '23'
#    jdkArchitectureOption: 'x64'
#    jdkSourceOption: 'PreInstalled'
#  displayName: 'Install Java'
- script: |
    curl -L -o jdk23.tar.gz https://download.oracle.com/java/23/latest/jdk-23_linux-x64_bin.tar.gz
    mkdir -p $HOME/jdk23
    tar -xzf jdk23.tar.gz -C $HOME/jdk23 --strip-components=1
    echo "##vso[task.setvariable variable=JAVA_HOME]$HOME/jdk23"
    echo "##vso[task.setvariable variable=PATH]$HOME/jdk23/bin:$PATH"
    java -version
  displayName: 'Install Java 23'

- bash: |
    mvn spotless:apply
    mvn -N wrapper:wrapper
    chmod +x ./mvnw
    apt install openjdk-23




- task: BlackDuckSecurityScan@2
  inputs:
    scanType: 'blackducksca'
    blackduckScaUrl: '$(SCA_URL)'
    blackduckScaToken: '$(SCA_ACCESS_TOKEN)'