trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  - group: Coverity_Evan

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
  displayName: 'Install Java'
- bash: |
    mvn spotless:apply
    mvn -N wrapper:wrapper
    chmod +x ./mvnw

- task: BlackDuckSecurityScan@2
  inputs:
    networkSslTrustAll: true
    scanType: 'coverity'
    coverityUrl: '$(COVERITY_URL)'
    coverityUser: '$(COVERITY_USERNAME)'
    coverityUserPassword: '$(COVERITY_TOKEN)'
    coverityLocal: true
    coverityProjectName: 'webgoat'
    coverityStreamName: 'webgoat'
    coverityBuildCommand: './mvnw clean install -DskipTests'
    coverityCleanCommand: './mvnw clean'