trigger:
- none

#pool:
#  default

#variables:
#  - group: Polaris

steps:
- script: |
    mvn --version
    java --version
  displayName: 'Version check'

- task: BlackDuckSecurityScan@2
  inputs:
    scanType: 'polaris'
    polarisServerUrl: 'https://poc.polaris.blackduck.com'
    polarisAccessToken: '$(POLARIS_ACCESSTOKEN)'
    polarisAssessmentTypes: 'SAST,SCA'
    polarisTestScaType: 'SCA-Package'
    polarisWaitForScan: false
    polarisApplicationName: 'Evan Onboarding'

- task: BlackDuckSecurityScan@2
  inputs:
    scanType: 'polaris'
    polarisServerUrl: 'https://poc.polaris.blackduck.com'
    polarisAccessToken: '$(POLARIS_ACCESSTOKEN)'
    polarisAssessmentTypes: 'SCA'
    polarisTestScaType: 'SCA-Signature'
    polarisWaitForScan: false
    polarisApplicationName: 'Evan Onboarding'