trigger:

- none

pool:
  vmImage: ubuntu-latest

variables:
  - group: Coverity_Evan

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '21'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
  displayName: 'Install Java'
- bash: |
    mvn spotless:apply
    mvn -N wrapper:wrapper
    chmod +x ./mvnw

- script: |
    java -version
  displayName: 'Print Java version'

- task: BlackDuckSecurityScan@2
  inputs:
    networkSslTrustAll: true
    scanType: 'coverity'
    coverityUrl: '$(COVERITY_URL)'
    coverityUser: '$(COVERITY_USERNAME)'
    coverityUserPassword: '$(COVERITY_TOKEN)'
    coverityProjectName: 'webgoat'
    coverityStreamName: 'webgoat'
    coverityBuildCommand: './mvnw install'
    coverityCleanCommand: './mvnw clean'