name: CI-Coverity-Basic
on:
  push:
    branches: [main, master, develop, stage, release]
  pull_request:
    branches: [main, master, develop, stage, release]
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
            java-version: 23
            distribution: temurin
            cache: maven
      - name: Set environment variable to bypass TLS verification
        run: echo "echo GIT_SSL_NO_VERIFY=true" >> $GITHUB_ENV && echo "BRIDGE_NETWORK_SSL_TRUST_ALL=true" >> $GITHUB_ENV
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Coverity Scan
        uses: blackduck-inc/black-duck-security-scan@v2
        with:
          ### SCANNING: Required fields
          coverity_url: ${{ vars.COVERITY_URL }}
          coverity_user: ${{ secrets.COVERITY_USER }}
          coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
                            
          ### POLICY ENFORCEMENT: Break build on full scan when encounter oustanding issues
          coverity_policy_view: ${{ github.event_name != 'pull_request' && 'Outstanding Issues' || '' }}
                            
          ### PULL REQUEST COMMENTS:
          coverity_prComment_enabled: true
          
          # Required when PR comments is enabled
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # Sets the SSL trust to true
          git_ssl_no_verify: true

          ### Perform local analysis with full toolkit
          # coverity_local: true
          
          # include_diagnostics: true
#    - name: Save Logs
#      if: always()
#      uses: actions/upload-artifact@v4
#      with:
#        name: bridge-logs
#        path: ${{ github.workspace }}/.bridge
#        include-hidden-files: true
