name: CI-Coverity-Basic
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
            java-version: 21
            distribution: temurin
            cache: maven
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Coverity Scan
        uses: blackduck-inc/black-duck-security-scan@v2
        with:
          ### SCANNING: Required fields
          #coverity_url: ${{ vars.COVERITY_URL }}
          #coverity_user: ${{ secrets.COVERITY_USER }}
          #coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
                            
          ### Coverity Connect users - Uncomment below
          # coverity_local: true
          
          ### POLICY ENFORCEMENT: Uncomment to break build on policy
          # coverity_policy_view: 'Outstanding Issues' 
                            
          ### PULL REQUEST COMMENTS:
          coverity_prComment_enabled: true
          github_token: ${{ secrets.GITHUB_TOKEN }} # Required when PR comments is enabled 
                            
          ### Mark build status if policy violating issues are found
          # mark_build_status: 'success'
                            
      ### Uncomment below configuration to add custom logic based on return status
      # - name: cmdLine
      #   id: cmdLine
      #   run: |
      #     EXIT_CODE=${{ steps.black-duck-security-scan.outputs.status }}
      #     echo "Black Duck Security Scan exit status - $EXIT_CODE"

      - name: Save Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bridge-logs
          path: ${{ github.workspace }}/.bridge
          include-hidden-files: true
