name: CI-Polaris-Basic
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
            java-version: 23
            distribution: temurin
            cache: maven

      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Polaris Scan
        uses: blackduck-inc/black-duck-security-scan@v2
        with:
          ### SCANNING: Required fields
          polaris_server_url: ${{ vars.POLARIS_SERVER_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_assessment_types: "SCA,SAST"
          polaris_application_name: "Evan Onboarding"
        
          ### SCANNING OPTIONAL
          detect_search_depth: 20 # SCA scan folder search depth
          
          ### SCANNING OPTIONAL: Pull Request comments
          polaris_prComment_enabled: true
          github_token: ${{ secrets.GITHUB_TOKEN }} # Required when Pull Request comments field enabled
          
          ### ENABLE OPTIONAL SCAN REPORTS
          polaris_reports_sarif_create: "true"
          # polaris_upload_sarif_report: "true"

                ### Mark build status if policy violating issues are found
        # mark_build_status: 'success'

                ### Uncomment below configuration to add custom logic based on return status
        # - name: cmdLine
        #   id: cmdLine
        #   run: |
        #     EXIT_CODE=${{ steps.black-duck-security-scan.outputs.status }}
        #     echo "Black Duck Security Scan exit status - $EXIT_CODE"
      - name: Save Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bridge-logs
          path: ${{ github.workspace }}/.bridge
          include-hidden-files: true
